### ISSUE TITLE
您好 抱歉打扰 但您的脚本的GF页面被删了

### ISSUE THREAD

**Issue by kevinluo6191** [QingXia-Ela/unlock-bilibili-PcBrowser-comment#1]
RT

**Comment by kevinluo6191** [comment]
![image](https://github.com/user-attachments/assets/e9c79d4b-40c9-46b1-bc36-7d15a75539fb)

**Comment by QingXia-Ela** [comment]
脚本已弃用，b站将改用 lit 做评论区，推荐改用更稳定的脚本如 Bilibili-evolved
